name: Bug Report
description: Report a bug or issue with the ASO skill
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below with as much detail as possible.

  - type: dropdown
    id: module
    attributes:
      label: Affected Module
      description: Which ASO skill module is affected?
      options:
        - keyword_analyzer.py
        - metadata_optimizer.py
        - competitor_analyzer.py
        - aso_scorer.py
        - ab_test_planner.py
        - localization_helper.py
        - review_analyzer.py
        - launch_checklist.py
        - itunes_api.py (lib)
        - scraper.py (lib)
        - ASO agents (aso-master, aso-research, etc.)
        - GitHub workflows
        - Documentation
        - Other / Not sure
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform is affected?
      options:
        - Apple App Store
        - Google Play Store
        - Both platforms
        - Not platform-specific
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Example: metadata_optimizer.py generates a title with 35 characters for Apple App Store, exceeding the 30-character limit"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import metadata_optimizer
        2. Call optimize_title() with input "My Super Amazing Fitness App for Health"
        3. See that output is 35 characters
        4. Apple App Store limit is 30 characters
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "Title should be truncated or optimized to fit within 30 characters for Apple App Store"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: "Title was not truncated and exceeds character limit"
    validations:
      required: true

  - type: textarea
    id: character-limits
    attributes:
      label: Character Limit Validation Issue
      description: If this bug relates to character limits, provide details
      placeholder: |
        - Platform: Apple App Store
        - Field: Title
        - Limit: 30 characters
        - Actual: 35 characters
        - Value: "My Super Amazing Fitness App for Health"
    validations:
      required: false

  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: What Python version are you using?
      options:
        - "3.13"
        - "3.12"
        - "3.11"
        - "3.10"
        - "3.9"
        - "3.8"
        - "3.7"
        - Other (specify in additional context)
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        - OS: macOS 14.0
        - Installation: user-level (~/.claude/skills/)
        - Claude Code version: 1.2.3
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem (screenshots, error messages, logs)
      placeholder: |
        Error traceback:
        ```
        Traceback (most recent call last):
          ...
        ```
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all required information above
          required: true
        - label: This is a bug, not a feature request (use Feature Request template for new features)
          required: true
