name: Feature Request
description: Suggest a new feature or enhancement for the ASO skill
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New ASO analysis capability
        - Enhanced metadata optimization
        - New platform support
        - Improved keyword analysis
        - Better A/B testing tools
        - Localization improvements
        - New ASO agent
        - GitHub workflow improvement
        - Documentation enhancement
        - Other
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Target Module
      description: Which module would this feature affect or extend?
      options:
        - keyword_analyzer.py
        - metadata_optimizer.py
        - competitor_analyzer.py
        - aso_scorer.py
        - ab_test_planner.py
        - localization_helper.py
        - review_analyzer.py
        - launch_checklist.py
        - New module (specify below)
        - ASO agents
        - GitHub workflows
        - Documentation
        - Multiple modules
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform Impact
      description: Which platform(s) would this feature affect?
      options:
        - Apple App Store only
        - Google Play Store only
        - Both platforms
        - Not platform-specific
        - New platform (specify below)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the problem or use case this feature would address
      placeholder: |
        Example: As an app marketer, I need to analyze trending keywords in my category to identify new opportunities. Currently, I have to manually check keyword trends, which is time-consuming.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature
      placeholder: |
        Example: Add a new function `analyze_trending_keywords()` to keyword_analyzer.py that:
        1. Accepts category and time period (7, 30, 90 days)
        2. Returns keywords with increasing search volume
        3. Provides trend direction (up, stable, down)
        4. Includes competition analysis for trending keywords
    validations:
      required: true

  - type: textarea
    id: aso-impact
    attributes:
      label: ASO Impact
      description: How would this feature improve ASO results?
      placeholder: |
        Example: This feature would help app developers:
        - Identify emerging keywords before competitors
        - Optimize metadata for growing search terms
        - Improve organic visibility by 15-20%
        - Reduce keyword research time from 2 hours to 15 minutes
    validations:
      required: true

  - type: textarea
    id: character-limits
    attributes:
      label: Platform Constraints
      description: If this affects metadata, specify character limits and platform requirements
      placeholder: |
        - Apple App Store: Title (30), Subtitle (30), Keywords (100)
        - Google Play Store: Title (50), Short Description (80)
        - Validation logic needed: Yes/No
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        Example: I tried using external keyword tools, but they don't integrate with the ASO skill workflow and require manual data entry.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my ASO workflow
        - High - Would significantly improve my results
        - Medium - Nice to have enhancement
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: example-data
    attributes:
      label: Example Data or Output
      description: Provide example input/output or mockup
      placeholder: |
        Input:
        ```python
        analyze_trending_keywords(
            category="Health & Fitness",
            period_days=30,
            min_trend_score=10
        )
        ```

        Expected Output:
        ```python
        [
            {
                "keyword": "AI workout planner",
                "trend": "up",
                "trend_score": 25,
                "current_volume": 15000,
                "previous_volume": 12000,
                "competition": "low"
            },
            ...
        ]
        ```
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references
      placeholder: |
        - Related issues: #123
        - External references: https://example.com/aso-trends
        - Screenshots: [attach if applicable]
    validations:
      required: false

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Would you be willing to contribute?
      options:
        - label: I would like to implement this feature myself
          required: false
        - label: I can provide testing and feedback
          required: false
        - label: I can help with documentation
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and PRs to avoid duplicates
          required: true
        - label: I have provided a clear use case and proposed solution
          required: true
        - label: This feature aligns with ASO best practices
          required: true
        - label: This is a feature request, not a bug report (use Bug Report template for bugs)
          required: true
