name: General Feedback & Ideas
description: Share feedback, ideas, or suggestions that don't fit other templates
title: "[FEEDBACK] "
labels: ["feedback", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        We value your feedback! Share your thoughts, ideas, or general suggestions about the ASO skill.

  - type: dropdown
    id: feedback-type
    attributes:
      label: Feedback Type
      description: What type of feedback are you providing?
      options:
        - General praise/appreciation
        - User experience improvement
        - Workflow suggestion
        - Performance feedback
        - ASO strategy idea
        - Integration suggestion
        - Design/UX feedback
        - Community/collaboration idea
        - Question (not a bug)
        - Other
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area of Focus
      description: Which area does your feedback relate to?
      options:
        - Keyword analysis
        - Metadata optimization
        - Competitor analysis
        - A/B testing
        - Localization
        - Review analysis
        - Launch planning
        - ASO agents
        - GitHub workflows
        - Documentation
        - Installation/setup
        - Overall ASO skill experience
        - Other
    validations:
      required: false

  - type: textarea
    id: feedback
    attributes:
      label: Your Feedback
      description: Share your thoughts, ideas, or suggestions
      placeholder: |
        Example: I've been using the ASO skill for 3 months and it's saved me 10+ hours per week on keyword research. One idea: It would be great if the skill could automatically detect when keywords are becoming saturated in the market and suggest alternatives.
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Expected Impact
      description: How would this improve your ASO workflow or results?
      placeholder: |
        Example: This would help me stay ahead of competition by pivoting to less saturated keywords before my rankings drop.
    validations:
      required: false

  - type: dropdown
    id: priority-level
    attributes:
      label: How Important Is This?
      description: How much would this improve your experience?
      options:
        - Game-changer - Would significantly improve my results
        - High value - Would save considerable time/effort
        - Nice to have - Would be a pleasant addition
        - Low priority - Just a small improvement
        - Just sharing thoughts - No specific priority
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Your ASO Context
      description: Help us understand your use case (optional but helpful)
      placeholder: |
        - Role: Indie app developer / Marketing manager / ASO specialist
        - Apps managed: 1-3 / 4-10 / 10+
        - Platforms: Apple / Google / Both
        - Experience with skill: < 1 month / 1-3 months / 3+ months
        - Primary use case: Launch / optimization / competitor tracking
    validations:
      required: false

  - type: textarea
    id: additional-thoughts
    attributes:
      label: Additional Thoughts
      description: Anything else you'd like to share?
      placeholder: |
        Any other context, examples, or ideas
    validations:
      required: false

  - type: checkboxes
    id: follow-up
    attributes:
      label: Follow-up
      description: Are you open to follow-up discussion?
      options:
        - label: I'm open to discussing this feedback further
          required: false
        - label: I'd be willing to test proposed solutions
          required: false
        - label: I'd like to be notified of related updates
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm
      options:
        - label: I have searched existing issues to see if this has been discussed
          required: true
        - label: This is feedback/idea, not a bug (use Bug Report for bugs)
          required: true
